# Dockerizing postgreSQL database

# not tested yet

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: store
    ports:
      - 5432:5432
    volumes:
      # defining the volume for the database, so that the data is persistent, named xcakes
      - xcakes:/var/lib/postgresql/data
  xcake-backend:
    build: ./docker-xcakes/pastelito-backend
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file: ./.env
    environment:
      DB_HOST: ${DB_HOST}
      #DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      #DB_USER: ${DB_USER}
      #DB_PASSWORD: ${DB_PASSWORD}
      DB_LINK: ${DB_LINK}
      JWT_SECRET: ${JWT_SECRET}
    #volumes:
      #- ./pastel-backend:/app
      #- /app/node_modules
  xcake-frontend:
    build: ./docker-f-xcakes/x-cakes
    ports:
      - 5173:5173
    depends_on:
      - xcake-backend
# declaring the volume so it can be used among other services
volumes:
  xcakes:

